### ISSUE TITLE
Black is the new ... well .. missing  ;)

### ISSUE THREAD

**Issue by jmls** [danlevan/google-material-color#12]
in https://material.google.com/style/color.html#color-color-palette there is a "Black" palette with just a "white" entry

This seems to be missing from the list of colors in this lib

**Comment by 8lueberry** [comment]
Hey @jmls,

The black and white palette is available as `Black` and `White` with the default `500` values.

https://github.com/danlevan/google-material-color/blob/master/src/colors.js#L299
https://github.com/danlevan/google-material-color/blob/master/src/colors.js#L311

**Comment by jmls** [comment]
ah - indeed it is - however, in my defence, I was looking at the colors in the readme, not the source ;)

> Colors
> Red, Pink, Purple, Deep Purple, Indigo, Blue, Light Blue, Cyan, Teal, Green, Light Green, Lime, Yellow, Amber, Orange, Deep Orange, Brown, Grey, Blue Grey
