### ISSUE TITLE
Feature request: Text color

### ISSUE THREAD

**Issue by Antariano** [danlevan/google-material-color#8]
As you can see from the [Google Material color specs](http://www.google.it/design/spec/style/color.html#color-color-palette) certain colors require different text colors (black or white).

![image](https://cloud.githubusercontent.com/assets/1273284/10765307/6224c58c-7cd2-11e5-83b0-19d4ef856d50.png)

It would be quite useful to have this available.

**Comment by danlevan** [comment]
I agree.. would be useful :) I'll add the text colors when I have time :)

**Comment by Antariano** [comment]
Actually I'm not exactly sure on the correct terminology. Is it foreground? ¯\_(ツ)_/¯

**Comment by danlevan** [comment]
Hehe, I think just `text` colour would be fine..

**Comment by jmls** [comment]
was this ever implemented ?

**Comment by 8lueberry** [comment]
Yeah just merged the PR for the text colour :)
